# Basic Example - Azure Terraform Naming Module
#
# This example demonstrates basic usage of the naming module
# to generate consistent names for common Azure resources.

terraform {
  required_version = ">= 1.0"
}

# Configure the naming module
module "naming" {
  source = "../.."

  cloud_acronym = "azc" # Azure Commercial
  prefix        = "contoso"
  workload      = "webapp"
  environment   = "dev"
  location      = "eastus"
}

# Example outputs showing generated names
output "example_names" {
  description = "Example resource names generated by the module"
  value = {
    resource_group          = module.naming.resource_group
    virtual_network         = module.naming.virtual_network
    subnet                  = module.naming.subnet
    network_security_group  = module.naming.network_security_group
    storage_account         = module.naming.storage_account
    key_vault               = module.naming.key_vault
    app_service_plan        = module.naming.app_service_plan
    web_app                 = module.naming.web_app
    sql_server              = module.naming.sql_server
    sql_database            = module.naming.sql_database
    log_analytics_workspace = module.naming.log_analytics_workspace
    application_insights    = module.naming.application_insights
  }
}

# Show the base naming components
output "base_name" {
  description = "Base name without resource type abbreviation"
  value       = module.naming.base_name
}

output "all_names_map" {
  description = "Map of all available resource type names"
  value       = module.naming.names
}
